version: '3'
services:
  nginx:
    image: celsosanchez/4-dvop:nginx
    ports:
      - "8080:8080"
  haproxy:
    image: celsosanchez/4-dvop:haproxy
    ports:
      - "80:80"
    depends_on:
      - nginx

