version: '3'
services:
  nginx-host:
    image: celsosanchez/cv:nginx
    ports:
      - "8080:8080"
  nginx-reverse:
    image: celsosanchez/cv:reverse
    ports:
      - "80:80"
    depends_on:
      - nginx-host

