 #4dvop-app.yaml
---
- hosts: prod
  become: true
  tasks:
    - name: Deploy 4dvop-nginx
      docker_container:
        name: nginx
        hostname: nginx
        image: celsosanchez/nginx-4dvop
        state: started
        ports:
          - "8080:8080"
    - name: Deploy 4dvop-haproxy
      docker_container:
        name: haproxy
        hostname: haproxy
        image: celsosanchez/haproxy-4dvop
        state: started
        links:
          - nginx:nginx
        ports:
          - "80:80"
