 #4dvop-app.yaml
---
- hosts: ec2
  gather_facts: False
  tasks:
    # - name: Deploy nginx
    #   docker_container:
    #     name: cv
    #     hostname: cv
    #     image: celsosanchez/cv-nginx
    #     state: started
    #     ports:
    #       - "3000:80"
    - name: test echo
      shell:
        "echo working"
    # - name: Deploy 4dvop-haproxy
    #   docker_container:
    #     name: haproxy
    #     hostname: haproxy
    #     image: celsosanchez/haproxy-4dvop
    #     state: started
    #     links:
    #       - nginx:nginx
    #     ports:
    #       - "80:80"
