---
- hosts: ec2
  become: true
  tasks:
  
     - name: delete previous docker container
       shell: docker rm -f cv

  
     - name: delete previous image 
       shell: docker image rm celsosanchez/cv-nginx


 
     - name: run docker container
       shell: docker run -dti -p 3000:80 --name cv  celsosanchez/cv-nginx:latest 
 